/* Write your PL/SQL query statement below */
SELECT D.NAME AS DEPARTMENT, E.NAME AS EMPLOYEE, E.SALARY
FROM EMPLOYEE E, DEPARTMENT D
WHERE E.DEPARTMENTID = D.ID
AND E.SALARY IN (SELECT MAX(E2.SALARY)
    FROM EMPLOYEE E2
    WHERE E2.DEPARTMENTID = E.DEPARTMENTID
);